version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "production"
      SPRING_DATASOURCE_URL: jdbc:mysql://ec2-3-39-229-110.ap-northeast-2.compute.amazonaws.com:3306/euro?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: euro
    ports:
      - "3306:3306"
