#server:
#  port: 7070

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

#  datasource:
#    url: jdbc:mysql://localhost:3306/europlanner?serverTimezone=UTC&characterEncoding=UTF-8
#    username: "root"
#    password: "1234"
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect

  webflux:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Content-Type,Authorization

jwt:
  secret: YOUR_SECRET_KEY
  expiration: 7200000 # 토큰이 만료되기까지의 시간 (밀리초 단위, 여기서는 2시간)

google:
  client:
    id: 74162317259-6pvbl6taro72s16tuldct2r906vfma04.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: http://localhost:7070/google/login

naver:
  client:
    id: QZ4Tt1rkD62cvojsp35E
    secret: eA0mRGjoez
  redirect:
    uri: http://localhost:7070/naver/login

kakao:
  client:
    id: f7db335e160a0711caa399186a502461
  redirect:
    uri: http://localhost:7070/kakao/login

amadeus:
  api_key: U8WYISIFa0dyYIIBWKWaBP7XmQJmbKue
  api_secret: 998AEJyKQcS3LmVY
